/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.jsansalone.jpaint.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

import org.jsansalone.jpaint.ui.editor.CoordenadaListener;
import org.jsansalone.jpaint.ui.editor.Editor;
import org.jsansalone.jpaint.ui.editor.EditorEnums;
import org.jsansalone.jpaint.ui.editor.EditorEnums.TipoCoordenada;
import org.jsansalone.jpaint.ui.editor.EditorEnums.TipoForma;

/**
 *
 * @author Jonathan
 */
public class JPaintUI extends javax.swing.JFrame {

    private Editor editor;
    
    /**
     * Creates new form JPaintUI
     */
    public JPaintUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/org/jsansalone/jpaint/ui/images/icon.png")));
        pnlFerramentas.add(tbFormas);
        pnlFerramentas.add(tbTipoPreenchimento);
        pnlFerramentas.add(tbEspessura);
        pnlFerramentas.add(tbTipoTraco);
        pnlFerramentas.add(tbCores);
        editor = new Editor();
        editor.getController().addCoordenadaListener(new CoordenadaListener() {
			@Override
			public void trataCoordenada(int x, int y) {
				lblCoordenada.setText(x + " x " + y);
			}
			@Override
			public TipoCoordenada getTipoCoordenada() {
				return TipoCoordenada.MOUSE;
			}
		});
        pnlRoot.add(editor,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbFormas = new javax.swing.JToolBar();
        btnQuadrado = new javax.swing.JToggleButton();
        btnCirculo = new javax.swing.JToggleButton();
        btnLinha = new javax.swing.JToggleButton();
        btnTexto = new javax.swing.JToggleButton();
        btnLapis = new javax.swing.JToggleButton();
        btnApagar = new javax.swing.JToggleButton();
        btgFormas = new javax.swing.ButtonGroup();
        tbEspessura = new javax.swing.JToolBar();
        btnEspessura1 = new javax.swing.JToggleButton();
        btnEspessura2 = new javax.swing.JToggleButton();
        btnEspessura3 = new javax.swing.JToggleButton();
        btgEspessura = new javax.swing.ButtonGroup();
        tbTipoTraco = new javax.swing.JToolBar();
        btnTracoContinuo = new javax.swing.JToggleButton();
        btnTracoTracejado = new javax.swing.JToggleButton();
        btgTipoTraco = new javax.swing.ButtonGroup();
        tbTipoPreenchimento = new javax.swing.JToolBar();
        btnFormaVazia = new javax.swing.JToggleButton();
        btnFormaPreenchida = new javax.swing.JToggleButton();
        btgTipoPreenchimento = new javax.swing.ButtonGroup();
        tbCores = new javax.swing.JToolBar();
        btnCorLinha = new javax.swing.JButton();
        btnCorFundo = new javax.swing.JButton();
        pnlFerramentas = new javax.swing.JPanel();
        pnlStatus = new javax.swing.JPanel();
        lblCoordenada = new javax.swing.JLabel();
        pnlRoot = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mniSalvar = new javax.swing.JMenuItem();
        mniSalvarComo = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        mniSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniGrade = new javax.swing.JCheckBoxMenuItem();
        mniGuias = new javax.swing.JCheckBoxMenuItem();
        mniRegua = new javax.swing.JCheckBoxMenuItem();

        tbFormas.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbFormas.setRollover(true);
        tbFormas.setMaximumSize(new java.awt.Dimension(37, 231));
        tbFormas.setMinimumSize(new java.awt.Dimension(37, 231));
        tbFormas.setPreferredSize(new java.awt.Dimension(37, 231));

        btgFormas.add(btnQuadrado);
        btnQuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/square_20x20.png"))); // NOI18N
        btnQuadrado.setSelected(true);
        btnQuadrado.setToolTipText("Retângulo");
        btnQuadrado.setFocusable(false);
        btnQuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuadrado.setIconTextGap(0);
        btnQuadrado.setMaximumSize(new java.awt.Dimension(35, 35));
        btnQuadrado.setMinimumSize(new java.awt.Dimension(35, 35));
        btnQuadrado.setPreferredSize(new java.awt.Dimension(35, 35));
        btnQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadradoActionPerformed(evt);
            }
        });
        tbFormas.add(btnQuadrado);

        btgFormas.add(btnCirculo);
        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/circle_30x30.png"))); // NOI18N
        btnCirculo.setToolTipText("Círculo");
        btnCirculo.setFocusable(false);
        btnCirculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCirculo.setIconTextGap(0);
        btnCirculo.setMaximumSize(new java.awt.Dimension(35, 35));
        btnCirculo.setMinimumSize(new java.awt.Dimension(35, 35));
        btnCirculo.setPreferredSize(new java.awt.Dimension(35, 35));
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });
        tbFormas.add(btnCirculo);

        btgFormas.add(btnLinha);
        btnLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/line_30x30.png"))); // NOI18N
        btnLinha.setToolTipText("Linha");
        btnLinha.setFocusable(false);
        btnLinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLinha.setIconTextGap(0);
        btnLinha.setMaximumSize(new java.awt.Dimension(35, 35));
        btnLinha.setMinimumSize(new java.awt.Dimension(35, 35));
        btnLinha.setPreferredSize(new java.awt.Dimension(35, 35));
        btnLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinhaActionPerformed(evt);
            }
        });
        tbFormas.add(btnLinha);

        btgFormas.add(btnTexto);
        btnTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/text_30x30.png"))); // NOI18N
        btnTexto.setToolTipText("Texto");
        btnTexto.setFocusable(false);
        btnTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTexto.setIconTextGap(0);
        btnTexto.setMaximumSize(new java.awt.Dimension(35, 35));
        btnTexto.setMinimumSize(new java.awt.Dimension(35, 35));
        btnTexto.setPreferredSize(new java.awt.Dimension(35, 35));
        btnTexto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextoActionPerformed(evt);
            }
        });
        tbFormas.add(btnTexto);

        btgFormas.add(btnLapis);
        btnLapis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/pencil_30x30.png"))); // NOI18N
        btnLapis.setToolTipText("Lápis");
        btnLapis.setFocusable(false);
        btnLapis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapis.setIconTextGap(0);
        btnLapis.setMaximumSize(new java.awt.Dimension(35, 35));
        btnLapis.setMinimumSize(new java.awt.Dimension(35, 35));
        btnLapis.setPreferredSize(new java.awt.Dimension(35, 35));
        btnLapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapisActionPerformed(evt);
            }
        });
        tbFormas.add(btnLapis);

        btgFormas.add(btnApagar);
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/eraser_27x30.png"))); // NOI18N
        btnApagar.setToolTipText("Borracha");
        btnApagar.setFocusable(false);
        btnApagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagar.setIconTextGap(0);
        btnApagar.setMaximumSize(new java.awt.Dimension(35, 35));
        btnApagar.setMinimumSize(new java.awt.Dimension(35, 35));
        btnApagar.setPreferredSize(new java.awt.Dimension(35, 35));
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        tbFormas.add(btnApagar);

        tbEspessura.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbEspessura.setRollover(true);

        btgEspessura.add(btnEspessura1);
        btnEspessura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/line_esp1_30x30.png"))); // NOI18N
        btnEspessura1.setSelected(true);
        btnEspessura1.setToolTipText("Linha fina");
        btnEspessura1.setFocusable(false);
        btnEspessura1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspessura1.setIconTextGap(0);
        btnEspessura1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnEspessura1.setMinimumSize(new java.awt.Dimension(35, 35));
        btnEspessura1.setPreferredSize(new java.awt.Dimension(35, 35));
        btnEspessura1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspessura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspessura1ActionPerformed(evt);
            }
        });
        tbEspessura.add(btnEspessura1);

        btgEspessura.add(btnEspessura2);
        btnEspessura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/line_esp2_30x30.png"))); // NOI18N
        btnEspessura2.setToolTipText("Linha média");
        btnEspessura2.setFocusable(false);
        btnEspessura2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspessura2.setIconTextGap(0);
        btnEspessura2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnEspessura2.setMinimumSize(new java.awt.Dimension(35, 35));
        btnEspessura2.setPreferredSize(new java.awt.Dimension(35, 35));
        btnEspessura2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspessura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspessura2ActionPerformed(evt);
            }
        });
        tbEspessura.add(btnEspessura2);

        btgEspessura.add(btnEspessura3);
        btnEspessura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/line_esp3_30x30.png"))); // NOI18N
        btnEspessura3.setToolTipText("Linha grossa");
        btnEspessura3.setFocusable(false);
        btnEspessura3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspessura3.setIconTextGap(0);
        btnEspessura3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnEspessura3.setMinimumSize(new java.awt.Dimension(35, 35));
        btnEspessura3.setPreferredSize(new java.awt.Dimension(35, 35));
        btnEspessura3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspessura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspessura3ActionPerformed(evt);
            }
        });
        tbEspessura.add(btnEspessura3);

        tbTipoTraco.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbTipoTraco.setRollover(true);

        btgTipoTraco.add(btnTracoContinuo);
        btnTracoContinuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/line_30x30.png"))); // NOI18N
        btnTracoContinuo.setSelected(true);
        btnTracoContinuo.setToolTipText("Linha contínua");
        btnTracoContinuo.setFocusable(false);
        btnTracoContinuo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTracoContinuo.setIconTextGap(0);
        btnTracoContinuo.setMaximumSize(new java.awt.Dimension(35, 35));
        btnTracoContinuo.setMinimumSize(new java.awt.Dimension(35, 35));
        btnTracoContinuo.setPreferredSize(new java.awt.Dimension(35, 35));
        btnTracoContinuo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTracoContinuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTracoContinuoActionPerformed(evt);
            }
        });
        tbTipoTraco.add(btnTracoContinuo);

        btgTipoTraco.add(btnTracoTracejado);
        btnTracoTracejado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/line_dash_30x30.png"))); // NOI18N
        btnTracoTracejado.setToolTipText("Linha tracejada");
        btnTracoTracejado.setFocusable(false);
        btnTracoTracejado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTracoTracejado.setIconTextGap(0);
        btnTracoTracejado.setMaximumSize(new java.awt.Dimension(35, 35));
        btnTracoTracejado.setMinimumSize(new java.awt.Dimension(35, 35));
        btnTracoTracejado.setPreferredSize(new java.awt.Dimension(35, 35));
        btnTracoTracejado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTracoTracejado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTracoTracejadoActionPerformed(evt);
            }
        });
        tbTipoTraco.add(btnTracoTracejado);

        tbTipoPreenchimento.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbTipoPreenchimento.setRollover(true);

        btgTipoPreenchimento.add(btnFormaVazia);
        btnFormaVazia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/square_20x20.png"))); // NOI18N
        btnFormaVazia.setSelected(true);
        btnFormaVazia.setToolTipText("Forma vazia");
        btnFormaVazia.setFocusable(false);
        btnFormaVazia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFormaVazia.setIconTextGap(0);
        btnFormaVazia.setMaximumSize(new java.awt.Dimension(35, 35));
        btnFormaVazia.setMinimumSize(new java.awt.Dimension(35, 35));
        btnFormaVazia.setPreferredSize(new java.awt.Dimension(35, 35));
        btnFormaVazia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFormaVazia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormaVaziaActionPerformed(evt);
            }
        });
        tbTipoPreenchimento.add(btnFormaVazia);

        btgTipoPreenchimento.add(btnFormaPreenchida);
        btnFormaPreenchida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jsansalone/jpaint/ui/images/filled_30x30.png"))); // NOI18N
        btnFormaPreenchida.setToolTipText("Forma preenchida");
        btnFormaPreenchida.setFocusable(false);
        btnFormaPreenchida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFormaPreenchida.setIconTextGap(0);
        btnFormaPreenchida.setMaximumSize(new java.awt.Dimension(35, 35));
        btnFormaPreenchida.setMinimumSize(new java.awt.Dimension(35, 35));
        btnFormaPreenchida.setPreferredSize(new java.awt.Dimension(35, 35));
        btnFormaPreenchida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFormaPreenchida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormaPreenchidaActionPerformed(evt);
            }
        });
        tbTipoPreenchimento.add(btnFormaPreenchida);

        tbCores.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbCores.setRollover(true);

        btnCorLinha.setBackground(new java.awt.Color(0, 0, 0));
        btnCorLinha.setToolTipText("Cor da linha");
        btnCorLinha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCorLinha.setFocusable(false);
        btnCorLinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCorLinha.setMaximumSize(new java.awt.Dimension(35, 35));
        btnCorLinha.setMinimumSize(new java.awt.Dimension(35, 35));
        btnCorLinha.setPreferredSize(new java.awt.Dimension(35, 35));
        btnCorLinha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCorLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorLinhaActionPerformed(evt);
            }
        });
        tbCores.add(btnCorLinha);

        btnCorFundo.setBackground(new java.awt.Color(255, 255, 255));
        btnCorFundo.setToolTipText("Cor do preenchimento");
        btnCorFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCorFundo.setFocusable(false);
        btnCorFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCorFundo.setMaximumSize(new java.awt.Dimension(35, 35));
        btnCorFundo.setMinimumSize(new java.awt.Dimension(35, 35));
        btnCorFundo.setPreferredSize(new java.awt.Dimension(35, 35));
        btnCorFundo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCorFundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorFundoActionPerformed(evt);
            }
        });
        tbCores.add(btnCorFundo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Paint");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlFerramentas.setMaximumSize(new java.awt.Dimension(100, 32767));
        pnlFerramentas.setMinimumSize(new java.awt.Dimension(50, 70));
        pnlFerramentas.setPreferredSize(new java.awt.Dimension(50, 479));
        pnlFerramentas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        getContentPane().add(pnlFerramentas, java.awt.BorderLayout.LINE_START);

        pnlStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlStatus.setMaximumSize(new java.awt.Dimension(32767, 25));
        pnlStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        pnlStatus.setPreferredSize(new java.awt.Dimension(700, 25));
        pnlStatus.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblCoordenada.setText("000 x 000");
        pnlStatus.add(lblCoordenada);

        getContentPane().add(pnlStatus, java.awt.BorderLayout.PAGE_END);

        pnlRoot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlRoot.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        mnuArquivo.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuArquivo.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuArquivo.add(jMenuItem2);

        mniSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniSalvar.setText("Salvar");
        mniSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalvarActionPerformed(evt);
            }
        });
        mnuArquivo.add(mniSalvar);

        mniSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniSalvarComo.setText("Salvar como");
        mniSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalvarComoActionPerformed(evt);
            }
        });
        mnuArquivo.add(mniSalvarComo);
        mnuArquivo.add(separator);

        mniSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mniSair);

        menuBar.add(mnuArquivo);

        jMenu1.setText("Ferramentas");

        mniGrade.setText("Grade");
        mniGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGradeActionPerformed(evt);
            }
        });
        jMenu1.add(mniGrade);

        mniGuias.setText("Guias");
        mniGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGuiasActionPerformed(evt);
            }
        });
        jMenu1.add(mniGuias);

        mniRegua.setText("Régua");
        mniRegua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReguaActionPerformed(evt);
            }
        });
        jMenu1.add(mniRegua);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        sair();
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_mniSalvarActionPerformed

    private void mniSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalvarComoActionPerformed
        salvarComo();
    }//GEN-LAST:event_mniSalvarComoActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        editor.setCursor(EditorEnums.TipoCursor.TIPO_CURSOR_DESENHO);
        editor.getEstado().setForma(TipoForma.FORMA_CIRCULO);
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnEspessura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspessura2ActionPerformed
        editor.getEstado().setEspessura(EditorEnums.TipoEspessura.LINHA_MEDIA);
    }//GEN-LAST:event_btnEspessura2ActionPerformed

    private void btnQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadradoActionPerformed
        editor.setCursor(EditorEnums.TipoCursor.TIPO_CURSOR_DESENHO);
        editor.getEstado().setForma(TipoForma.FORMA_RETANGULO);
    }//GEN-LAST:event_btnQuadradoActionPerformed

    private void btnLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhaActionPerformed
        editor.setCursor(EditorEnums.TipoCursor.TIPO_CURSOR_DESENHO);
        editor.getEstado().setForma(TipoForma.FORMA_LINHA);
    }//GEN-LAST:event_btnLinhaActionPerformed

    private void btnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextoActionPerformed
        editor.setCursor(EditorEnums.TipoCursor.TIPO_CURSOR_TEXTO);
        editor.getEstado().setForma(TipoForma.FORMA_TEXTO);
    }//GEN-LAST:event_btnTextoActionPerformed

    private void btnLapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapisActionPerformed
        editor.setCursor(EditorEnums.TipoCursor.TIPO_CURSOR_LAPIS);
        editor.getEstado().setForma(TipoForma.FORMA_LAPIS);
    }//GEN-LAST:event_btnLapisActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        editor.setCursor(EditorEnums.TipoCursor.TIPO_CURSOR_BORRACHA);
        editor.getEstado().setForma(TipoForma.FORMA_BORRACHA);
    }//GEN-LAST:event_btnApagarActionPerformed

    private void mniGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGradeActionPerformed
        editor.getEstado().setGrade(mniGrade.isSelected());
    }//GEN-LAST:event_mniGradeActionPerformed

    private void mniGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGuiasActionPerformed
        editor.getEstado().setGuias(mniGuias.isSelected());
    }//GEN-LAST:event_mniGuiasActionPerformed

    private void mniReguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReguaActionPerformed
        editor.getEstado().setRegua(mniRegua.isSelected());
    }//GEN-LAST:event_mniReguaActionPerformed

    private void btnFormaPreenchidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormaPreenchidaActionPerformed
        editor.getEstado().setPreenchimento(EditorEnums.TipoPreenchimento.FORMA_PREENCHIDA);
    }//GEN-LAST:event_btnFormaPreenchidaActionPerformed

    private void btnTracoTracejadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTracoTracejadoActionPerformed
        editor.getEstado().setTraco(EditorEnums.TipoTraco.TRACEJADO);
    }//GEN-LAST:event_btnTracoTracejadoActionPerformed

    private void btnCorLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorLinhaActionPerformed
        Color cor = getCor("Cor da linha");
        btnCorLinha.setBackground(cor);
        editor.getEstado().setCorDaLinha(cor);
    }//GEN-LAST:event_btnCorLinhaActionPerformed

    private void btnCorFundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorFundoActionPerformed
        Color cor = getCor("Cor do preenchimento");
        btnCorFundo.setBackground(cor);
        editor.getEstado().setCorDoPreenchimento(cor);
    }//GEN-LAST:event_btnCorFundoActionPerformed

    private void btnFormaVaziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormaVaziaActionPerformed
        editor.getEstado().setPreenchimento(EditorEnums.TipoPreenchimento.FORMA_VAZIA);
    }//GEN-LAST:event_btnFormaVaziaActionPerformed

    private void btnTracoContinuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTracoContinuoActionPerformed
        editor.getEstado().setTraco(EditorEnums.TipoTraco.CONTINUO);
    }//GEN-LAST:event_btnTracoContinuoActionPerformed

    private void btnEspessura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspessura1ActionPerformed
        editor.getEstado().setEspessura(EditorEnums.TipoEspessura.LINHA_FINA);
    }//GEN-LAST:event_btnEspessura1ActionPerformed

    private void btnEspessura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspessura3ActionPerformed
        editor.getEstado().setEspessura(EditorEnums.TipoEspessura.LINHA_GROSSA);
    }//GEN-LAST:event_btnEspessura3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Deseja salvar o desenho?") == JOptionPane.YES_OPTION){
        	salvarComo();
        }
    	editor.novo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        File arquivo = getArquivo(false);
        if(arquivo != null){
        	try {
				BufferedImage image = ImageIO.read(arquivo);
				editor.carregarImagem(image);
			} catch (IOException e) {
				e.printStackTrace();
			}
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private Color getCor(String titulo){
        JDialog d = new JDialog(this);
        d.setLayout(new BorderLayout());
        d.setModal(true);
        d.setTitle(titulo);
        d.setSize(400, 400);
        d.setLocationRelativeTo(this);
        JColorChooser chooser = new JColorChooser();
        d.add(chooser, BorderLayout.CENTER);
        d.setVisible(true);
        Color cor = chooser.getColor();
        return cor;
    }
    
    private void sair(){
        System.exit(0);
    }
    
    private void salvar(){
        salvarComo();
    }
    
    private void salvarComo(){
        File arquivo = getArquivo(true);
        if(arquivo != null){
	        try {
				ImageIO.write(editor.getImagem(), "png", arquivo);
			} catch (Exception e) {
				e.printStackTrace();
			}
        }
    }
    
    private File getArquivo(boolean salvar){
    	JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
			@Override
			public String getDescription() {
				return "PNG";
			}
			@Override
			public boolean accept(File f) {
				return f.getName().endsWith(".png") || f.getName().endsWith(".PNG");
			}
		});
        if((salvar ? chooser.showSaveDialog(this) : chooser.showOpenDialog(this)) == JFileChooser.APPROVE_OPTION){
	        File f = chooser.getSelectedFile();
	        if(f != null){
	        	return f;
	        }
        }
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgEspessura;
    private javax.swing.ButtonGroup btgFormas;
    private javax.swing.ButtonGroup btgTipoPreenchimento;
    private javax.swing.ButtonGroup btgTipoTraco;
    private javax.swing.JToggleButton btnApagar;
    private javax.swing.JToggleButton btnCirculo;
    private javax.swing.JButton btnCorFundo;
    private javax.swing.JButton btnCorLinha;
    private javax.swing.JToggleButton btnEspessura1;
    private javax.swing.JToggleButton btnEspessura2;
    private javax.swing.JToggleButton btnEspessura3;
    private javax.swing.JToggleButton btnFormaPreenchida;
    private javax.swing.JToggleButton btnFormaVazia;
    private javax.swing.JToggleButton btnLapis;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnQuadrado;
    private javax.swing.JToggleButton btnTexto;
    private javax.swing.JToggleButton btnTracoContinuo;
    private javax.swing.JToggleButton btnTracoTracejado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblCoordenada;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JCheckBoxMenuItem mniGrade;
    private javax.swing.JCheckBoxMenuItem mniGuias;
    private javax.swing.JCheckBoxMenuItem mniRegua;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSalvar;
    private javax.swing.JMenuItem mniSalvarComo;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JPanel pnlFerramentas;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JToolBar tbCores;
    private javax.swing.JToolBar tbEspessura;
    private javax.swing.JToolBar tbFormas;
    private javax.swing.JToolBar tbTipoPreenchimento;
    private javax.swing.JToolBar tbTipoTraco;
    // End of variables declaration//GEN-END:variables
}
